# Generated by Django 4.2.3 on 2025-07-19 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_id",
            field=models.FloatField(default=1),
        ),
    ]
