# Generated by Django 4.2.3 on 2025-07-18 00:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CostSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "material_cost_open_cell",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "material_cost_closed_cell",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "labor_cost_per_sqft",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "equipment_overhead",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                (
                    "default_profit_margin",
                    models.DecimalField(decimal_places=2, default=20, max_digits=5),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
