# Generated by Django 4.2.3 on 2025-07-20 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_costsettings_bi_bale_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsettings",
            name="roll_of_batts_ext_exp_yld",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
