# Generated by Django 4.2.3 on 2025-07-20 02:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("companyprofile", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyUsers",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254, null=True)),
                ("phone", models.IntegerField(null=True)),
                ("role", models.CharField(max_length=255)),
                ("hr_rate", models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="phone",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="companyprofile",
            name="site",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
