# Generated by Django 4.2.3 on 2025-07-19 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("spray_area", models.FloatField()),
                ("material_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("labor_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "equipment_cost",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("overhead_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("profit_margin", models.DecimalField(decimal_places=2, max_digits=5)),
                ("final_bid", models.DecimalField(decimal_places=2, max_digits=12)),
                ("date_generated", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
